# Use the latest 2.1 version of CircleCI pipeline process engine.
# See: https://circleci.com/docs/configuration-reference
version: 2.1

jobs:
  local-build-test:
    docker:
      - image: circleci/rust:latest
    steps:
      - checkout
      - run:
          name: Set up Rust environment
          command: |
            rustup default nightly
            rustup component add rustfmt clippy
      - run:
          name: Build Babylon contract
          command: |
            cargo build
      - run:
          name: Test generating schema
          command: |
            cargo schema
      - run:
          name: Check formats and run unit tests
          command: |
            cargo test

  wasm-build-check-integration:
    docker:
      - image: circleci/rust:latest
    steps:
      - checkout
      - setup_remote_docker
      - run:
          name: Set Rust nightly as default toolchain
          command: |
            rustup default nightly
      - run:
          name: Build optimised Wasm binary
          command: |
            cargo install cargo-run-script
            cargo run-script optimize
      - run:
          name: Install cosmwasm-check
          command: |
            cargo install cosmwasm-check
      - run:
          name: Check the Wasm binary's validity against Wasm VM
          command: |
            cosmwasm-check /home/circleci/project/artifacts/storage_contract.wasm
      - persist_to_workspace:
          root: /home/circleci/project/artifacts
          paths:
            - storage_contract.wasm

  # This job roughly follows the instructions from https://circleci.com/blog/publishing-to-github-releases-via-circleci/
  build_and_upload_contracts:
    docker:
      - image: circleci/rust:latest
    working_directory: /home/circleci/project
    steps:
      - checkout:
          path: /home/circleci/project
      - setup_remote_docker
      - run:
          name: Make temporary bin
          command: mkdir -p /tmp/bin
      - run:
          name: Install ghr
          command: wget https://github.com/tcnksm/ghr/releases/download/v0.14.0/ghr_v0.14.0_linux_amd64.tar.gz -O - | tar -zxvf - -C /tmp/bin --wildcards --strip-components 1 */ghr
      - run:
          name: Set Rust nightly as default toolchain
          command: |
            rustup default nightly
      - run:
          name: Build optimised Wasm binary
          command: |
            cargo install cargo-run-script
            cargo run-script optimize
      - persist_to_workspace:
          root: /home/circleci/project/artifacts
          paths:
            - storage_contract.wasm
            - checksums.txt
      - run:
          name: Show data
          command: |
            ls -l artifacts
            cat artifacts/checksums.txt
      - run:
          name: Publish artifacts on GitHub
          command: |
            TAG="$CIRCLE_TAG"
            TITLE="$TAG"
            BODY="Attached there are some build artifacts generated at this tag. Those are for development purposes only! Please use crates.io to find the packages of this release."
            /tmp/bin/ghr -t "$GITHUB_TOKEN" \
              -u "$CIRCLE_PROJECT_USERNAME" -r "$CIRCLE_PROJECT_REPONAME" \
              -c "$CIRCLE_SHA1" \
              -n "$TITLE" -b "$BODY" \
              -replace \
              "$TAG" ./artifacts/

  build_and_upload_schemas:
    docker:
      - image: rust:1.67.0
    working_directory: /home/circleci/project
    steps:
      - checkout:
          path: /home/circleci/project
      - run:
          name: Make temporary bin
          command: mkdir -p /tmp/bin
      - run:
          name: Install ghr
          command: wget https://github.com/tcnksm/ghr/releases/download/v0.14.0/ghr_v0.14.0_linux_amd64.tar.gz -O - | tar -zxvf - -C /tmp/bin --wildcards --strip-components 1 */ghr
      - run:
          name: Build and run schema generator
          command: |
            cargo schema
      - run:
          name: Show data
          command: ls -l ./schema
      - run:
          name: Publish schemas on GitHub
          command: |
            TAG="$CIRCLE_TAG"
            TITLE="$TAG"
            BODY="Attached there are some schemas and build artifacts generated at this tag. Those are for development purposes only! Please use crates.io to find the packages of this release."
            /tmp/bin/ghr -t "$GITHUB_TOKEN" \
              -u "$CIRCLE_PROJECT_USERNAME" -r "$CIRCLE_PROJECT_REPONAME" \
              -c "$CIRCLE_SHA1" \
              -n "$TITLE" -b "$BODY" \
              -replace \
              "$TAG" ./schema/

# Orchestrate jobs using workflows
# See: https://circleci.com/docs/configuration-reference/#workflows
workflows:
  deploy:
    jobs:
      - build_and_upload_contracts:
          filters:
            tags:
              only: /^v[0-9]+\.[0-9]+\.[0-9]+.*/
            branches:
              only: release-v0.1.1
      - build_and_upload_schemas:
          filters:
            tags:
              only: /^v[0-9]+\.[0-9]+\.[0-9]+.*/
            branches:
              only: release-v0.1.1
